import type { Metadata } from "next";
import localFont from "next/font/local";
import "primeicons/primeicons.css";
import "primereact/resources/themes/lara-light-cyan/theme.css";
import "primeflex/primeflex.css";
import "primereact/resources/primereact.css";

import "./globals.css";

import { Header } from "@/components/core/header";
import { Footer } from "@/components/core/footer";
import { PrimeReactProvider } from "primereact/api";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />

        <PrimeReactProvider>{children}</PrimeReactProvider>

        <Footer />
      </body>
    </html>
  );
}
